### ISSUE TITLE
last update doesn't work anymore!

### ISSUE THREAD

**Issue by mjegulla** [roukou3/DCTL#1]
I updated to latest version but it doesn't work. No red circle and adjustments don't react!
I then reverted to the previous version and everything again works fine!

Thank you for the good work. 
Keep it up!

**Comment by roukou3** [comment]
Thank you for feedback.
I found _fdivide(float, float) not work on OpenCL. (Works fine on CUDA)
I changed that to _fdivide(float, int). (Works on both CUDA & OpenCL)

**Comment by mjegulla** [comment]
wow, thank you!
Laowa_4.0mm_f2.8.dctl and Meike_6.5mm_f2.0.dctl work now, but PTGui11.dctl doesn't.

**Comment by roukou3** [comment]
Thank you. I found an incompatibility in PTGui11.dctl.

**Comment by mjegulla** [comment]
works fine now, thank you so much!
